### Introduction, importing libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

import warnings
warnings.filterwarnings("ignore")

I'm importing the bottle dataset from kaggle. The dataset will be called bottle_df. Let's inspect the first 5 rows of the dataframe with .head().

In [2]:
bottle_df = pd.read_csv("bottle.csv")
bottle_df.head()

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,Oxy_Âµmol/Kg,BtlNum,RecInd,T_prec,T_qual,S_prec,S_qual,P_qual,O_qual,SThtaq,O2Satq,ChlorA,Chlqua,Phaeop,Phaqua,PO4uM,PO4q,SiO3uM,SiO3qu,NO2uM,NO2q,NO3uM,NO3q,NH3uM,NH3q,C14As1,C14A1p,C14A1q,C14As2,C14A2p,C14A2q,DarkAs,DarkAp,DarkAq,MeanAs,MeanAp,MeanAq,IncTim,LightP,R_Depth,R_TEMP,R_POTEMP,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_O2,R_O2Sat,R_SIO3,R_PO4,R_NO3,R_NO2,R_NH4,R_CHLA,R_PHAEO,R_PRES,R_SAMP,DIC1,DIC2,TA1,TA2,pH2,pH1,DIC Quality Comment
0,1,1,054.0 056.0,19-4903CR-HY-060-0930-05400560-0000A-3,0,10.50,33.440,NaN,25.649,NaN,NaN,NaN,3,1.0,NaN,2.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,0.0,10.50,10.50,33.440,25.64,233.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,054.0 056.0,19-4903CR-HY-060-0930-05400560-0008A-3,8,10.46,33.440,NaN,25.656,NaN,NaN,NaN,3,2.0,NaN,2.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,8.0,10.46,10.46,33.440,25.65,232.5,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,054.0 056.0,19-4903CR-HY-060-0930-05400560-0010A-7,10,10.46,33.437,NaN,25.654,NaN,NaN,NaN,7,2.0,NaN,3.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,10.0,10.46,10.46,33.437,25.65,232.8,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,054.0 056.0,19-4903CR-HY-060-0930-05400560-0019A-3,19,10.45,33.420,NaN,25.643,NaN,NaN,NaN,3,2.0,NaN,2.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,19.0,10.45,10.45,33.420,25.64,234.1,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,054.0 056.0,19-4903CR-HY-060-0930-05400560-0020A-7,20,10.45,33.421,NaN,25.643,NaN,NaN,NaN,7,2.0,NaN,3.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,20.0,10.45,10.45,33.421,25.64,234.0,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
bottle_df.shape

(864863, 74)

In [4]:
bottle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864863 entries, 0 to 864862
Data columns (total 74 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Cst_Cnt              864863 non-null  int64
 1   Btl_Cnt              864863 non-null  int64
 2   Sta_ID               864863 non-null  object
 3   Depth_ID             864863 non-null  object
 4   Depthm               864863 non-null  int64
 5   T_degC               853900 non-null  float64
 6   Salnty               817509 non-null  float64
 7   O2ml_L               696201 non-null  float64
 8   STheta               812174 non-null  float64
 9   O2Sat                661274 non-null  float64
 10  Oxy_Âµmol/Kg          661268 non-null  float64
 11  BtlNum               118667 non-null  float64
 12  RecInd               864863 non-null  int64
 13  T_prec               853900 non-null  float64
 14  T_qual               23127 non-null   float64
 15  S_prec               817509 non-null  float64
 16  S_qual               74914 non-null   float64
 17  P_qual               673755 non-null  float64
 18  O_qual               184676 non-null  float64
 19  SThtaq               65823 non-null   float64
 20  O2Satq               217797 non-null  float64
 21  ChlorA               225272 non-null  float64
 22  Chlqua               639166 non-null  float64
 23  Phaeop               225271 non-null  float64
 24  Phaqua               639170 non-null  float64
 25  PO4uM                413317 non-null  float64
 26  PO4q                 451786 non-null  float64
 27  SiO3uM               354091 non-null  float64
 28  SiO3qu               510866 non-null  float64
 29  NO2uM                337576 non-null  float64
 30  NO2q                 529474 non-null  float64
 31  NO3uM                337403 non-null  float64
 32  NO3q                 529933 non-null  float64
 33  NH3uM                64962 non-null   float64
 34  NH3q                 808299 non-null  float64
 35  C14As1               14432 non-null   float64
 36  C14A1p               12760 non-null   float64
 37  C14A1q               848605 non-null  float64
 38  C14As2               14414 non-null   float64
 39  C14A2p               12742 non-null   float64
 40  C14A2q               848623 non-null  float64
 41  DarkAs               22649 non-null   float64
 42  DarkAp               20457 non-null   float64
 43  DarkAq               840440 non-null  float64
 44  MeanAs               22650 non-null   float64
 45  MeanAp               20457 non-null   float64
 46  MeanAq               840439 non-null  float64
 47  IncTim               14437 non-null   object
 48  LightP               18651 non-null   float64
 49  R_Depth              864863 non-null  float64
 50  R_TEMP               853900 non-null  float64
 51  R_POTEMP             818816 non-null  float64
 52  R_SALINITY           817509 non-null  float64
 53  R_SIGMA              812007 non-null  float64
 54  R_SVA                812092 non-null  float64
 55  R_DYNHT              818206 non-null  float64
 56  R_O2                 696201 non-null  float64
 57  R_O2Sat              666448 non-null  float64
 58  R_SIO3               354099 non-null  float64
 59  R_PO4                413325 non-null  float64
 60  R_NO3                337411 non-null  float64
 61  R_NO2                337584 non-null  float64
 62  R_NH4                64982 non-null   float64
 63  R_CHLA               225276 non-null  float64
 64  R_PHAEO              225275 non-null  float64
 65  R_PRES               864863 non-null  int64
 66  R_SAMP               122006 non-null  float64
 67  DIC1                 1999 non-null    float64
 68  DIC2                 224 non-null     float64
 69  TA1                  2084 non-null    float64
 70  TA2                  234 non-null     float64
 71  pH2                  10 non-null      float64
 72  pH1                  84 non-null      float64
 73  DIC Quality Comment  55 non-null      object
dtypes: float64(65), int64(5), object(4)
memory usage: 488.3+ MB

As we can see, there are 74 columns, each corresponding to some mysterious names or shortcuts. In order to get some control, we will rename them to show explicitly what they mean.

In [5]:
columns = ["Cast Count", "Bottle Count", "Station ID", "Depth ID", "Depth", "Temperature", "Salinity",
           "O2_mL/L", "H2O Density", "O2 Sat", "O2_Âµmol/Kg", "Bottle No", "Record Indicator",
           "Temperature Precision", "Temperature Quality", "Salinity Precision", "Salinity Quality",
           "Pressure Quality", "O2 Quality", "H20_Density Quality", "O2_Saturation Quality",
           "Chlorophyll-a", "Chlorophyll-a Quality", "Phaeophytin_Concentration", "Phaeophytin Quality", "Phosphate Concentration",
           "Phosphate Quality", "Silicate Concentration", "Silicate Quality", "Nitrite Concentration",
           "Nitrite Quality", "Nitrate Concentration", "Nitrate Quality", "NH4 Concentration", "NH4 Quality",
           "C14_As1", "C14_As1 Precision", "C14_As1 Quality", "C14_As2", "C14_As2 Precision", "C14_As2 Quality",
           "C14_As_Dark", "C14_As_Dark Precision", "C14_As_Dark Quality", "Mean_C14_As", "Mean_C14_As Precision",
           "Mean_C14_As Quality", "Incubation Time", "Light Intensity", "Reported Depth", "Reported Temperature",
           "Reported Potential Temperature", "Reported Salinity", "Reported Potential Density",
           "Reported Specific Volume Anomaly", "Reported Dynamic Height", "Reported O2_mL/L", "Reported O2 Sat",
           "Reported Silicate Concentration", "Reported Phosphate Concentration", "Reported Nitrate Concentration",
           "Reported Nitrite Concentration", "Reported NH4 Concentration", "Reported Chlorophyll-a",
           "Reported Phaeophytin", "Pressure (decibars)", "Sample No", "Dissolved_Inorganic_Carbon1",
           "Dissolved_Inorganic_Carbon2", "Total Alkalinity1", "Total Alkalinity2", "pH2", "pH1",
           "DIC Quality Comment"
]
bottle_df.columns = columns
bottle_df.head()

,Cast Count,Bottle Count,Station ID,Depth ID,Depth,Temperature,Salinity,O2_mL/L,H2O Density,O2 Sat,O2_Âµmol/Kg,Bottle No,Record Indicator,Temperature Precision,Temperature Quality,Salinity Precision,Salinity Quality,Pressure Quality,O2 Quality,H20_Density Quality,O2_Saturation Quality,Chlorophyll-a,Chlorophyll-a Quality,Phaeophytin_Concentration,Phaeophytin Quality,Phosphate Concentration,Phosphate Quality,Silicate Concentration,Silicate Quality,Nitrite Concentration,Nitrite Quality,Nitrate Concentration,Nitrate Quality,NH4 Concentration,NH4 Quality,C14_As1,C14_As1 Precision,C14_As1 Quality,C14_As2,C14_As2 Precision,C14_As2 Quality,C14_As_Dark,C14_As_Dark Precision,C14_As_Dark Quality,Mean_C14_As,Mean_C14_As Precision,Mean_C14_As Quality,Incubation Time,Light Intensity,Reported Depth,Reported Temperature,Reported Potential Temperature,Reported Salinity,Reported Potential Density,Reported Specific Volume Anomaly,Reported Dynamic Height,Reported O2_mL/L,Reported O2 Sat,Reported Silicate Concentration,Reported Phosphate Concentration,Reported Nitrate Concentration,Reported Nitrite Concentration,Reported NH4 Concentration,Reported Chlorophyll-a,Reported Phaeophytin,Pressure (decibars),Sample No,Dissolved_Inorganic_Carbon1,Dissolved_Inorganic_Carbon2,Total Alkalinity1,Total Alkalinity2,pH2,pH1,DIC Quality Comment
0,1,1,054.0 056.0,19-4903CR-HY-060-0930-05400560-0000A-3,0,10.50,33.440,NaN,25.649,NaN,NaN,NaN,3,1.0,NaN,2.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,0.0,10.50,10.50,33.440,25.64,233.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,054.0 056.0,19-4903CR-HY-060-0930-05400560-0008A-3,8,10.46,33.440,NaN,25.656,NaN,NaN,NaN,3,2.0,NaN,2.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,8.0,10.46,10.46,33.440,25.65,232.5,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,054.0 056.0,19-4903CR-HY-060-0930-05400560-0010A-7,10,10.46,33.437,NaN,25.654,NaN,NaN,NaN,7,2.0,NaN,3.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,10.0,10.46,10.46,33.437,25.65,232.8,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,054.0 056.0,19-4903CR-HY-060-0930-05400560-0019A-3,19,10.45,33.420,NaN,25.643,NaN,NaN,NaN,3,2.0,NaN,2.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,19.0,10.45,10.45,33.420,25.64,234.1,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,054.0 056.0,19-4903CR-HY-060-0930-05400560-0020A-7,20,10.45,33.421,NaN,25.643,NaN,NaN,NaN,7,2.0,NaN,3.0,NaN,9.0,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,9.0,NaN,NaN,20.0,10.45,10.45,33.421,25.64,234.0,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Here, we are importing some more libraries which will be used to create 3 models.

In [6]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

The aim of the project will be to predict the water temperature, expressed in C degrees.

In [7]:
# ZakÅadajÄc, Å¼e 'Temperature' to nasza zmienna docelowa
target = "Temperature"

From now on, we are preprocessing data in order to get a DataFrame which will be viable to be used.

Preprocesing:
* We remove columns with too many missing values. We set the threshold at 30%
* We remove rows with missing search/target value
* We divide the data into test sets (20%) and training sets (80%).

We are also building a function that will be used to preprocess test and training data. It will separate numeric data from categorical data, remove columns with missing values, and finally ensure that the sets no longer contain null values.

In [9]:
# Krok 1: UsuÅ kolumny z zbyt duÅ¼Ä iloÅciÄ brakujÄcych wartoÅci przed podziaÅem
perc_null = (bottle_df.isnull().sum() / bottle_df.shape[0]).to_dict()
nn_cols = [col for col in bottle_df.columns if perc_null[col] <= 0.3]
df = bottle_df[nn_cols]

In [10]:
# Krok 2: UsuÅ wiersze z brakujÄcÄ wartoÅciÄ docelowÄ przed podziaÅem
df = df.dropna(subset=[target])

In [11]:
# Krok 3: PodziaÅ na zbiÃ³r treningowy i testowy
X = df.drop(target, axis=1)
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Definicja funkcji preprocess_data_simple
def preprocess_data_simple(df, drop_threshold=70, num_strategy="mean", fill_value=-999):
    data = df.copy()  # make a copy of the original dataframe

    # Drop columns with percent of missing values greater than the threshold
    #percent_missing = data.isna().sum() / data.shape[0] * 100
    #columns_to_drop = percent_missing[percent_missing > drop_threshold].index
    #data.drop(columns_to_drop, axis=1, inplace=True)

    # Separate numerical and categorical columns
    num_attributes = data.select_dtypes(include=['float64', 'int64']).columns
    cat_attributes = data.select_dtypes(include=['object']).columns

    # Create a SimpleImputer object for the numerical columns
    if num_strategy == "constant":
        numerical_imputer = SimpleImputer(fill_value=fill_value)
    else:
        numerical_imputer = SimpleImputer(strategy=num_strategy)

    # Impute missing values for numerical attributes
    data[num_attributes] = numerical_imputer.fit_transform(data[num_attributes])

    # Impute missing values for categorical columns
    data[cat_attributes] = data[cat_attributes].fillna(data[cat_attributes].mode().iloc[0])

    # Assert that there are no missing values in the prepared dataframe
    assert not data.isna().sum().sum()

    return data

In [13]:
# Zastosowanie funkcji preprocess_data_simple do danych treningowych
X_train = preprocess_data_simple(X_train, drop_threshold=70, num_strategy="mean", fill_value=-999)

# Zastosowanie funkcji preprocess_data_simple do danych testowych
X_test = preprocess_data_simple(X_test, drop_threshold=70, num_strategy="mean", fill_value=-999)

We will now check the dimensions of the training and test sets, we expect that they will have the same number of columns, but a different number of rows. Additionally, the proportion of test data (20%) to training data (80%) should be maintained.

In [14]:
# Kodowanie zmiennych kategorycznych na zbiorze treningowym i zastosowanie do zbioru testowego
cat_attributes = X_train.select_dtypes(include=['object']).columns

encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train[cat_attributes] = encoder.fit_transform(X_train[cat_attributes])
X_test[cat_attributes] = encoder.transform(X_test[cat_attributes])

# Sprawdzenie koÅcowych zbiorÃ³w danych
print("Wymiary zbioru treningowego:", X_train.shape)
print("Wymiary zbioru testowego:", X_test.shape)

Wymiary zbioru treningowego: (683120, 31)
Wymiary zbioru testowego: (170780, 31)

In [15]:
X_train.describe()

,Cast Count,Bottle Count,Station ID,Depth ID,Depth,Salinity,O2_mL/L,H2O Density,O2 Sat,O2_Âµmol/Kg,Record Indicator,Temperature Precision,Salinity Precision,Pressure Quality,Chlorophyll-a Quality,Phaeophytin Quality,NH4 Quality,C14_As1 Quality,C14_As2 Quality,C14_As_Dark Quality,Mean_C14_As Quality,Reported Depth,Reported Temperature,Reported Potential Temperature,Reported Salinity,Reported Potential Density,Reported Specific Volume Anomaly,Reported Dynamic Height,Reported O2_mL/L,Reported O2 Sat,Pressure (decibars)
count,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.0,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000,683120.000000
mean,17205.653147,434082.658043,1254.189216,341559.408379,228.721042,33.841405,3.382985,25.819928,57.109996,148.819434,4.700243,2.017126,2.719220,9.0,8.999857,8.999852,8.946808,8.999990,8.999990,8.999991,8.999989,228.721604,10.798492,10.840966,33.841387,25.811447,220.925089,0.433140,3.383017,57.122645,230.297921
std,10244.448152,249794.416245,589.283592,197199.746707,317.213421,0.451191,1.865760,1.175235,32.649283,79.376792,1.876448,0.148354,0.438852,0.0,0.010266,0.010477,0.495613,0.003201,0.003201,0.002964,0.003201,317.213183,4.245615,4.150373,0.451192,1.123869,91.214409,0.373848,1.865775,32.693560,320.637733
min,1.000000,1.000000,0.000000,0.000000,0.000000,28.431000,-0.010000,20.934000,-0.100000,-0.434900,3.000000,1.000000,2.000000,9.0,8.000000,8.000000,4.000000,8.000000,8.000000,8.000000,8.000000,0.000000,1.440000,0.000000,28.431000,20.934000,0.400000,0.000000,-0.010000,-0.100000,0.000000
25%,8351.000000,218581.750000,794.000000,170779.750000,48.000000,33.501000,1.860000,25.011000,30.900000,88.754018,3.000000,2.000000,2.000000,9.0,8.999857,8.999852,9.000000,9.000000,9.000000,9.000000,9.000000,48.000000,7.680000,7.850000,33.501000,25.000000,146.000000,0.147000,1.860000,30.800000,48.000000
50%,16960.000000,434256.500000,1153.000000,341559.500000,125.000000,33.841405,3.382985,25.898000,57.109996,148.819434,3.000000,2.000000,3.000000,9.0,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,125.000000,10.060000,10.340000,33.841387,25.890000,212.300000,0.363000,3.383017,57.122645,126.000000
75%,26667.000000,651552.500000,1667.000000,512339.250000,300.000000,34.182000,5.250000,26.622000,89.100000,226.515050,7.000000,2.000000,3.000000,9.0,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,300.000000,13.890000,13.750000,34.182000,26.620000,295.600000,0.620000,5.250000,89.300000,302.000000
max,34404.000000,864863.000000,2566.000000,683108.000000,5351.000000,37.034000,11.130000,250.784000,214.100000,485.701800,7.000000,3.000000,3.000000,9.0,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,5351.000000,31.140000,31.140000,37.034000,250.784000,683.400000,3.880000,11.130000,214.100000,5458.000000

In [16]:
X_test.head()

,Cast Count,Bottle Count,Station ID,Depth ID,Depth,Salinity,O2_mL/L,H2O Density,O2 Sat,O2_Âµmol/Kg,Record Indicator,Temperature Precision,Salinity Precision,Pressure Quality,Chlorophyll-a Quality,Phaeophytin Quality,NH4 Quality,C14_As1 Quality,C14_As2 Quality,C14_As_Dark Quality,Mean_C14_As Quality,Reported Depth,Reported Temperature,Reported Potential Temperature,Reported Salinity,Reported Potential Density,Reported Specific Volume Anomaly,Reported Dynamic Height,Reported O2_mL/L,Reported O2 Sat,Pressure (decibars)
296941,11355.0,296942.0,1321.0,-1.0,75.0,33.355000,5.620000,24.968000,95.300000,244.875200,7.0,2.0,3.00000,9.000000,9.000000,9.000000,9.000000,9.0,9.0,9.0,9.0,75.0,13.76,13.750000,33.355000,24.960000,299.90000,0.260000,5.620000,95.300000,75.0
640141,26253.0,640142.0,776.0,-1.0,11.0,33.631000,6.070000,24.939000,105.600000,264.490100,3.0,2.0,3.00000,8.999977,8.999802,8.999802,9.000000,9.0,9.0,9.0,9.0,11.0,14.90,14.900000,33.631000,24.930000,300.90000,0.030000,6.070000,105.600000,11.0
794625,31700.0,794626.0,519.0,-1.0,125.0,33.641000,3.382322,25.981000,57.078899,148.765709,5.0,2.0,3.00000,8.999977,9.000000,9.000000,9.000000,9.0,9.0,9.0,9.0,125.0,9.47,9.460000,33.641000,25.981000,204.10000,0.334000,3.382347,57.093247,126.0
99601,3364.0,99602.0,469.0,-1.0,236.0,33.841067,3.382322,25.817254,57.078899,148.765709,3.0,2.0,2.71982,9.000000,9.000000,9.000000,9.000000,9.0,9.0,9.0,9.0,236.0,7.73,10.847614,33.840864,25.809261,220.99428,0.431822,3.382347,57.093247,238.0
803227,32014.0,803228.0,901.0,-1.0,102.0,32.957000,5.580000,25.346000,87.300000,243.042600,3.0,2.0,3.00000,8.999977,8.999802,8.999802,8.947509,9.0,9.0,9.0,9.0,102.0,10.08,10.070000,32.957000,25.346000,264.00000,0.311000,5.580000,87.300000,102.0

In [17]:
X_test.describe()

,Cast Count,Bottle Count,Station ID,Depth ID,Depth,Salinity,O2_mL/L,H2O Density,O2 Sat,O2_Âµmol/Kg,Record Indicator,Temperature Precision,Salinity Precision,Pressure Quality,Chlorophyll-a Quality,Phaeophytin Quality,NH4 Quality,C14_As1 Quality,C14_As2 Quality,C14_As_Dark Quality,Mean_C14_As Quality,Reported Depth,Reported Temperature,Reported Potential Temperature,Reported Salinity,Reported Potential Density,Reported Specific Volume Anomaly,Reported Dynamic Height,Reported O2_mL/L,Reported O2 Sat,Pressure (decibars)
count,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.0,170780.0,170780.000000,170780.0,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000,170780.000000
mean,17195.441580,433801.391808,1253.616354,6.957887,227.631924,33.841067,3.382322,25.817254,57.078899,148.765709,4.707114,2.017239,2.719820,8.999977,8.999802,8.999802,8.947509,9.0,9.0,8.999994,9.0,227.632428,10.804518,10.847614,33.840864,25.809261,220.994280,0.431822,3.382347,57.093247,229.200527
std,10239.538545,249640.904938,589.742747,2325.412603,315.496617,0.449184,1.864935,0.980166,32.618825,79.320467,1.878033,0.149074,0.438421,0.007259,0.012098,0.012098,0.492718,0.0,0.0,0.002420,0.0,315.496282,4.236687,4.140963,0.454733,0.980581,90.974568,0.372940,1.864937,32.660912,318.889402
min,1.000000,8.000000,-1.000000,-1.000000,0.000000,29.402000,-0.010000,21.204000,-0.100000,-0.434896,3.000000,1.000000,2.000000,6.000000,8.000000,8.000000,4.000000,9.0,9.0,8.000000,9.0,0.000000,1.440000,1.110000,4.570000,21.200000,39.900000,0.000000,-0.010000,-0.100000,0.000000
25%,8323.000000,217794.750000,794.000000,-1.000000,48.000000,33.502000,1.870000,25.015000,31.100000,89.086915,3.000000,2.000000,2.000000,9.000000,8.999802,8.999802,9.000000,9.0,9.0,9.000000,9.0,48.000000,7.700000,7.870000,33.502000,25.010000,146.200000,0.150000,1.870000,31.000000,48.000000
50%,16947.000000,433978.500000,1153.000000,-1.000000,125.000000,33.841067,3.382322,25.893380,57.078899,148.765709,3.000000,2.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.0,9.0,9.000000,9.0,125.000000,10.070000,10.360000,33.840864,25.880000,212.700000,0.360000,3.382347,57.093247,126.000000
75%,26632.000000,650647.000000,1667.000000,-1.000000,300.000000,34.180000,5.240000,26.619000,88.985000,226.305150,7.000000,2.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.0,9.0,9.000000,9.0,300.000000,13.880000,13.740000,34.180000,26.610000,295.300000,0.619000,5.240000,89.100000,302.000000
max,34404.000000,864861.000000,2566.000000,679531.000000,5130.000000,36.463000,9.930000,27.859000,191.500000,433.270300,7.000000,3.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.0,9.0,9.000000,9.0,5130.000000,31.090000,31.090000,36.463000,27.820000,657.500000,3.840000,9.930000,191.500000,5226.000000

In [18]:
X_train = X_train.drop(columns=['Cast Count','Bottle Count','Station ID','Depth ID'])
X_test = X_test.drop(columns=['Cast Count','Bottle Count','Station ID','Depth ID'])

Now we will create a function to evaluate our models.

In [19]:
# Funkcja do oceny modelu
def evaluate(X_test, y_test, model):
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    return mse

### Models evaluation - regression, decisionTree, XGBooster

Below you can find a flow of processing and evaluating of models.
Models are fed with data, upgraded using tuning, trained and evaluated.
Metric used for model comparison is MSE.

In [20]:
# Definicja potoku przetwarzania
numeric_features = X_train.select_dtypes(include=['float64', 'int64']).columns
categorical_features = X_train.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

# Definicja modeli
pipeline_lr = Pipeline(steps=[('preprocessor', preprocessor),
                              ('regressor', LinearRegression())])

pipeline_dtr = Pipeline(steps=[('preprocessor', preprocessor),
                               ('regressor', DecisionTreeRegressor(random_state=42))])

pipeline_xgb = Pipeline(steps=[('preprocessor', preprocessor),
                               ('regressor', XGBRegressor(random_state=42))])

# Tuning modeli
param_grid_dtr = {
    'regressor__max_depth': [5, 10],
    'regressor__min_samples_split': [2, 5],
    'regressor__min_samples_leaf': [1, 2]
}

param_grid_xgb = {
    'regressor__n_estimators': [100],
    'regressor__learning_rate': [0.1],
    'regressor__max_depth': [5],
    'regressor__subsample': [0.8, 1.0]
}

grid_search_dtr = GridSearchCV(pipeline_dtr, param_grid_dtr, cv=5, scoring='neg_mean_squared_error')
grid_search_xgb = GridSearchCV(pipeline_xgb, param_grid_xgb, cv=5, scoring='neg_mean_squared_error')

# Trenowanie modeli
pipeline_lr.fit(X_train, y_train)
grid_search_dtr.fit(X_train, y_train)
grid_search_xgb.fit(X_train, y_train)

# Ocena modeli
def evaluate(X_test, y_test, model):
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    return mse

# Wyniki
print("MSE (Linear Regression):", evaluate(X_test, y_test, pipeline_lr))
print("Best Params (Decision Tree):", grid_search_dtr.best_params_)
print("MSE (Decision Tree):", evaluate(X_test, y_test, grid_search_dtr.best_estimator_))
print("Best Params (XGBoost):", grid_search_xgb.best_params_)
print("MSE (XGBoost):", evaluate(X_test, y_test, grid_search_xgb.best_estimator_))

MSE (Linear Regression): 8.339342520987016e-07
Best Params (Decision Tree): {'regressor__max_depth': 10, 'regressor__min_samples_leaf': 1, 'regressor__min_samples_split': 2}
MSE (Decision Tree): 3.571511056127222e-05
Best Params (XGBoost): {'regressor__learning_rate': 0.1, 'regressor__max_depth': 5, 'regressor__n_estimators': 100, 'regressor__subsample': 0.8}
MSE (XGBoost): 0.0034857866545485736

We will take a look at how first 5 samples are predicted.

In [21]:
# Podsumowanie dla pierwszych piÄciu prÃ³bek
tmp_test = X_test.iloc[:5].copy()  # Use copy to avoid SettingWithCopyWarning
tmp_test["pred"] = pipeline_lr.predict(tmp_test)
tmp_test["true"] = y_test.iloc[:5].values  # Ensure 'true' column matches the indexes of 'tmp_test'

print(tmp_test[["true", "pred"] + tmp_test.columns[:-2].tolist()])  # Display 'true' and 'pred' columns first

         true       pred  Depth   Salinity   O2_mL/L  H2O Density      O2 Sat  \
296941  13.76  13.759984   75.0  33.355000  5.620000    24.968000   95.300000
640141  14.90  14.899971   11.0  33.631000  6.070000    24.939000  105.600000
794625   9.47   9.469963  125.0  33.641000  3.382322    25.981000   57.078899
99601    7.73   7.729967  236.0  33.841067  3.382322    25.817254   57.078899
803227  10.08  10.079968  102.0  32.957000  5.580000    25.346000   87.300000

        O2_Âµmol/Kg  Record Indicator  Temperature Precision  \
296941  244.875200               7.0                    2.0
640141  264.490100               3.0                    2.0
794625  148.765709               5.0                    2.0
99601   148.765709               3.0                    2.0
803227  243.042600               3.0                    2.0

        Salinity Precision  Pressure Quality  Chlorophyll-a Quality  \
296941             3.00000          9.000000               9.000000
640141             3.00000          8.999977               8.999802
794625             3.00000          8.999977               9.000000
99601              2.71982          9.000000               9.000000
803227             3.00000          8.999977               8.999802

        Phaeophytin Quality  NH4 Quality  C14_As1 Quality  C14_As2 Quality  \
296941             9.000000     9.000000              9.0              9.0
640141             8.999802     9.000000              9.0              9.0
794625             9.000000     9.000000              9.0              9.0
99601              9.000000     9.000000              9.0              9.0
803227             8.999802     8.947509              9.0              9.0

        C14_As_Dark Quality  Mean_C14_As Quality  Reported Depth  \
296941                  9.0                  9.0            75.0
640141                  9.0                  9.0            11.0
794625                  9.0                  9.0           125.0
99601                   9.0                  9.0           236.0
803227                  9.0                  9.0           102.0

        Reported Temperature  Reported Potential Temperature  \
296941                 13.76                       13.750000
640141                 14.90                       14.900000
794625                  9.47                        9.460000
99601                   7.73                       10.847614
803227                 10.08                       10.070000

        Reported Salinity  Reported Potential Density  \
296941          33.355000                   24.960000
640141          33.631000                   24.930000
794625          33.641000                   25.981000
99601           33.840864                   25.809261
803227          32.957000                   25.346000

        Reported Specific Volume Anomaly  Reported Dynamic Height  \
296941                         299.90000                 0.260000
640141                         300.90000                 0.030000
794625                         204.10000                 0.334000
99601                          220.99428                 0.431822
803227                         264.00000                 0.311000

        Reported O2_mL/L  Reported O2 Sat  Pressure (decibars)
296941          5.620000        95.300000                 75.0
640141          6.070000       105.600000                 11.0
794625          3.382347        57.093247                126.0
99601           3.382347        57.093247                238.0
803227          5.580000        87.300000                102.0

We are quite happy with the results. There are some differences between real and predicted values, however there are no significant discrepancies.

### Testing by feeding real data
Below we will use some random data to check and compare how those 3 models we are predicting the temperature.

In [22]:
# Funkcja do przewidywania temperatury
def predict_temperature(values):
    if len(values) != len(X.columns):
        raise ValueError(f"Number of input values ({len(values)}) does not match number of features ({len(X.columns)})")

    input_df = pd.DataFrame([values], columns=X.columns)

    temp_lr = pipeline_lr.predict(input_df)[0]
    temp_dtr = grid_search_dtr.best_estimator_.predict(input_df)[0]
    temp_xgb = grid_search_xgb.best_estimator_.predict(input_df)[0]

    return {"Linear Regression": temp_lr, "Decision Tree": temp_dtr, "XGBoost": temp_xgb}

In [23]:
# PrzykÅadowe uÅ¼ycie
sample_values = [
    26253.0, 640142.0, 776.0, -1.0, 11.0, 33.631000, 6.070000, 24.939000, 105.600000,
    264.490100, 3.0, 2.0, 3.00000, 8.999977, 8.999802, 8.999802, 9.000000, 9.0, 9.0,
    9.0, 9.0, 11.0, 14.90, 14.900000, 33.631000, 24.930000, 300.90000, 0.030000,
    6.070000, 105.600000, 11.0
]
predictions = predict_temperature(sample_values)
print(predictions)

{'Linear Regression': 14.899970904324631, 'Decision Tree': 14.899989429175363, 'XGBoost': 14.91739}

As we can see, there are some discrepancies, however the goal is achived - all 3 models (regression, XGBooster, DecisionTree) are predicting water temperature at a level that satisfies us.